version: '2.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cmpaas
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cmpaas
      ME_CONFIG_MONGODB_ADMINPASSWORD: aWVafBlHL64ylXsc

  cmpaas-backend:
    image: lukasg18/cmpaas-backend:1.0.1
    restart: always
    links: 
      - "mongo:mongo"
    ports: 
      - "3000:3000"
    depends_on: 
      - "mongo"
    environment: 
      DB_URI: mongodb://mongo:27017/cmpaas?retryWrites=true&w=majority
      SMTP_CONF: smtps://cmpaas@gmail.com:Cmp@4sUFES@smtp.gmail.com
    
  cmpaas-frontend:
    image: lukasg18/cmpaas-frontend:1.0.1
    restart: always
    ports:
      - "80:80"